### PR TITLE
Updates the Menu

### PR DESCRIPTION
**Pull request by hallem**
This updates the menu for the system per our conversation. Here's the general layout with the new submenus:

````
0. Update All
1. Update Firmware
2. Select Cores
3. Download Assets
4. Backup Saves
5. Pocket Setup
   a. Download Platform Image Packs
   b. Generate Instance JSON Files (PC Engine CD)
   c. Generate Game & Watch ROMs
   d. Enable All Display Modes
   e. Go Back
6. Pocket Maintenance
   a. Reinstall Cores
   b. Uninstall Cores
   c. Go Back
8. Settings
9. Exit
````

### CODE REVIEW

**Comment by mattpannella** [comment]
doesnt need to be in the this PR (or maybe i can do it lol) but i think an "all" option would be useful for `Reinstall Cores`
since thatd be the equivalent of running pupdate update --clean

**Comment by hallem** [comment]
Yeah I agree. I was thinking of doing this with the more aggressive nuke option that was being discussed in the discord.

**Comment by mattpannella** [comment]
i added memories to the saves backup and merged that in here

**Comment by hallem** [comment]
> i added memories to the saves backup and merged that in here

you beat me to it! lol. I was working on this yesterday but then decided to get away from the computer.

**Pull request merged**
