### PR TITLE
Backup saves directory feature

### PR DESCRIPTION
**Pull request by hallem**
I added the ability to compress and backup the Saves directory. This can be done via a CLI verb as well as menu functionality. I also added settings in the config that will allow this to be automatically done during update all.

### CODE REVIEW

**Comment by mattpannella** [comment]
awesome, thanks! i'll take a look in a bit and test this out
also i apologize for the mess that is program.cs lol

**Comment by hallem** [comment]
lol no worries! I've been resisting the urge to reformat it, but if you're open to it, I've got some time to do the work lol

**Comment by mattpannella** [comment]
oh god it needs it. i mean the whole project does at this point, but especially that stuff
if you really want to...go for it
i have trouble finding the motivation to clean up my own mess lol

**Comment by hallem** [comment]
LOL you got it. I made a career out of doing stuff like that in the past.

**Pull request merged**
