### PR TITLE
fixed settings crash

### PR DESCRIPTION
**Pull request by mattpannella**
wasn't thinking and added a description to a setting we don't want in the settings menu

### CODE REVIEW

**Comment by mattpannella** [comment]
should resolve #289

**Comment by nopro83** [comment]
My PC keeps telling it is a virus! :(

**Comment by mattpannella** [comment]
it's a false positive you can look at the source code yourself

**Comment by nopro83** [comment]
But what can I do against it? Using Win 11.

**Comment by mattpannella** [comment]
I don't know i don't use windows defender. does it not let you whitelist programs?

**Comment by nopro83** [comment]
Yeah, I shut down Defender temporary and then it worked.

But I keep getting the error: "Error in framework - Missing 'BIOS' ID [259]" 
It doesn't happen every time, but quite regularly. 

Did you hear about that?

Thanks in advance for your answer!

**Comment by mattpannella** [comment]
you're missing the bios for whatever core that error appears on

**Comment by nopro83** [comment]
Didn't pupupdate load the bios files for itself?

**Pull request merged**
